service: dashboard-serverless-mysql-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  call:
    handler: handler.call
    events:
      - http:
          path: user
          method: post
          cors: true
      - http:
          path: users
          method: get
          cors: true
      - http:
          path: login
          method: post
          cors: true
